repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: debug-statements
  - id: check-ast

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.20
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v2.1.0
  hooks:
  - id: mypy
    additional_dependencies: [types-attrs, types-PyYAML, types-requests, types-pytz, types-croniter, types-freezegun]
