version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
