name: Publish packages
on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Build release packages
    runs-on: ubuntu-latest
    environment: publish
    permissions:  # for trusted publishing
      id-token: write

    steps:
    - uses: actions/checkout@master

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user

    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Publish release on pypi
      uses: pypa/gh-action-pypi-publish@release/v1
